version: 2
jobs:
  Release:
    docker:
      - image: circleci/node:20

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pnpm install

      - run:
          name: Gatsby Build
          command: ./node_modules/.bin/gatsby build

      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - Release:
          filters:
            branches:
              only: master
