name: CI Checks
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.9.0
          run_install: false

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "v20"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: TypeScript Compilation
        run: pnpm tscheck

      - name: Linting
        run: pnpm lint

      - name: Build website
        env:
          VITE_ENVIRONMENT: local
        run: pnpm build
